backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - label: "Page"
    name: "page"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
    
  - label: "Blog"
    name: "blog"
    folder: "posts"
    create: true
    identifier_field: name
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required:false }
      - { label: "Body", name: "body", widget: "markdown" }
